apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-django-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-django-app
  template:
    metadata:
      labels:
        app: python-django-app
    spec:
      containers:
      - name: python-django-app
        image: dexdv/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
