apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-django-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-django-app
  template:
    metadata:
      labels:
        app: python-django-app
    spec:
      containers:
      - name: python-django-app
        image: dexdv/aks
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-app
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  ingressClassName: python-app-app
  rules:
  - host: python-django-app.0b7f2fd77f894224b9af.eastus.aksapp.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-django-app
              port:
                number: 8000